### ISSUE TITLE
Recentemente não esta mais baixando legendas

### ISSUE THREAD

**Issue by rodultrazone** [igorklafke/legpy#1]
Boa noite,
Uso seu programa a algum tempo e é execelnte para baixar legendas de série, porém a uns 3 dias parou de funcionar ele acha a legenda diz que esta baixando porém não baixa.Sabe me ionformar se é algum bug no programa????.Fiz alguns testes novamente  e me parece que se o nome não for exatamente igual, o programa não baixa, encontra a legenda diz que esta baixando mais não faz o download.

**Comment by igorklafke** [comment]
Irei verificar. Pode ter sido alguma alteração que fizeram no site.

**Comment by igorklafke** [comment]
A última versão do aplicativo corrige os casos em que o nome da legenda não é exatamente igual ao nome do arquivo.
